# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [7]:
def share_bread(N, K):
    x = K // N
    y = K % N
    return x, y

assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [10]:
def leap_year(year):
    if year % 4 == 0 and year % 100 == 0 and year % 400 == 0:
        return "YOU SHALL PASS"

    return "YOU SHALL NOT PASS"

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [13]:
def amulet_area(a, b, c):
    S = (a+b+c)/2

    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [20]:
import numpy as np

def cal_euclidean(a, b):    
    return np.linalg.norm(a-b)

def cal_manhattan(a, b):
    return np.sum(np.abs(np.array(a) - np.array(b)))

def cal_cosine(a, b):    
    return np.dot(a, b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [21]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

25.592967784139454
61
-0.4847702115052894


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [29]:
my_array = np.random.uniform(0.0,1.0,100)
print(np.max(my_array), np.min(my_array))
print(my_array)

0.9849690587102085 0.005420596513821763
[0.35477294 0.20307021 0.65912529 0.95657019 0.89455054 0.42305081
 0.20338437 0.54903181 0.83147436 0.73728136 0.7599691  0.18506087
 0.59940803 0.63466732 0.18747185 0.67794917 0.66167827 0.63898427
 0.87908016 0.35585351 0.16058331 0.12671083 0.43194197 0.53610135
 0.0969499  0.41179851 0.25094199 0.30205839 0.5019142  0.53458568
 0.79481623 0.34384037 0.9034292  0.768245   0.32498539 0.65904335
 0.75806184 0.42150062 0.27239165 0.07155451 0.52815235 0.58283719
 0.66747149 0.58705648 0.85248579 0.96923378 0.7141165  0.01256026
 0.29981714 0.43582625 0.98496906 0.72353353 0.20792775 0.65532206
 0.73824841 0.37151387 0.28369901 0.1354602  0.22692274 0.83665669
 0.38862504 0.48236308 0.57635188 0.51021684 0.23894117 0.84492281
 0.71378293 0.19787719 0.92170625 0.34836688 0.24628134 0.45541324
 0.53323882 0.52370367 0.44283351 0.06945831 0.0054206  0.69550059
 0.68133744 0.0523733  0.12644261 0.94955459 0.46678325 0.31535373
 0.1010517  0.49317463

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [30]:
my_array = np.random.uniform(0, 50, (5, 6))
selected_column = np.max(my_array)
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[37.84266774 12.38253505  6.95802742 39.50973355 40.37835457  3.51437628]
 [14.55961681 17.36057043 46.49195903 37.36915072 41.34155439 17.76603834]
 [13.79216229 30.47282565 31.47678277 32.56084088 46.11246749 31.02487623]
 [ 6.44790522  9.66333392 20.21938289 16.84807188 41.77671408  5.17324828]
 [37.55515135  2.50974527 43.81187826 19.59987077 20.18274709  9.14760299]]
46.49195903126292


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [31]:
def get_unique_rows(X):
    return np.unique(X, axis=0)

In [32]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[5 5 4]
 [4 5 5]
 [4 4 5]
 [4 4 4]
 [4 4 5]
 [4 5 5]
 [5 4 4]
 [5 5 4]
 [5 4 4]
 [4 5 4]]


In [33]:
get_unique_rows(X)

array([[4, 4, 4],
       [4, 4, 5],
       [4, 5, 4],
       [4, 5, 5],
       [5, 4, 4],
       [5, 5, 4]])